kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: pure-vvols
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: csi.vsphere.vmware.com
parameters:
  storagepolicyname: "pure-vvols"
  # DatastoreURL: "ds:///vmfs/volumes/755cb3f0-1a4c3aae/"
  fstype: ext4
